version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  reviewers:
  - sokra
  labels:
  - dependencies
  versioning-strategy: widen
  ignore:
  - dependency-name: coffee-loader
    versions:
    - ">= 2.a, < 3"
  - dependency-name: cspell
    versions:
    - "> 4.2.5"
  - dependency-name: simple-git
    versions:
    - "> 2.27.0, < 3"
  - dependency-name: strip-ansi
    versions:
    - ">= 7.a, < 8"
  - dependency-name: ts-loader
    versions:
    - ">= 9.a, < 10"
  - dependency-name: typescript
    versions:
    - "> 4.2.0-dev.20201130"
  - dependency-name: typescript
    versions:
    - "> 4.2.0.pre.beta, < 4.3"
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.24
    - 14.14.26
    - 14.14.29
    - 14.14.30
    - 15.0.0
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.5.0
    - 32.0.0
    - 32.0.1
    - 32.0.3
    - 32.1.0
    - 32.1.1
    - 32.3.2
  - dependency-name: acorn
    versions:
    - 8.2.0
  - dependency-name: fork-ts-checker-webpack-plugin
    versions:
    - 6.2.2
    - 6.2.3
  - dependency-name: css-loader
    versions:
    - 5.1.2
    - 5.1.3
    - 5.1.4
    - 5.2.0
    - 5.2.3
  - dependency-name: core-js
    versions:
    - 3.11.0
    - 3.9.0
  - dependency-name: eslint
    versions:
    - 7.23.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.4
    - 24.1.5
    - 24.1.6
    - 24.1.7
    - 24.2.1
    - 24.3.0
    - 24.3.1
    - 24.3.2
    - 24.3.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: terser
    versions:
    - 5.6.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: mime-types
    versions:
    - 2.1.29
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.7
  - dependency-name: ts-loader
    versions:
    - 8.0.15
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.12.13
  - dependency-name: browserslist
    versions:
    - 4.16.2
  - dependency-name: date-fns
    versions:
    - 2.20.3
    - 2.21.0
